alias rollback='rake db:rollback && RAILS_ENV=test rake db:rollback'
alias migrate='rake db:migrate && RAILS_ENV=test rake db:migrate'
alias rt='bundle exec rake test'
alias rrt='bundle exec rescue rake test'
alias rc='rails console'
alias dieschema='git reset db/schema.rb && git checkout db/schema.rb'
alias rspec='time bundle exec rspec'
alias testtruncate='RAILS_ENV=test spring rake db:reset db:migrate > /dev/null'
