alias rollback='spring rake db:rollback && RAILS_ENV=test spring rake db:rollback'
alias migrate='spring rake db:migrate && RAILS_ENV=test spring rake db:migrate'
alias rt='rails c test'
alias rc='spring rails console'
alias dieschema='git reset db/schema.rb && git checkout db/schema.rb'
alias rspec='bundle exec rspec'
