alias search='aptitude search'
alias show='aptitude show'
alias instal='sudo apt-get install'
alias remove='sudo apt-get remove'
alias update='sudo apt-get update'
alias upgrade='sudo apt-get dist-upgrade'
